version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - docker_mariadb_data:/var/lib/mysql  # Volumen para persistir datos de MariaDB
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql  # Si deseas inicializar la base de datos con un archivo SQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8001:80"
    depends_on:
      - db
    
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./fastapi/app:/fastapi/app  # Volumen compartido para FastAPI (para persistencia de archivos y datos)

  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./apache/app:/usr/local/apache2/htdocs/

volumes:
  docker_mariadb_data:  # Volumen para la persistencia de datos de MariaDB
    driver: local
