version: '3.8'

networks:
  appnet:
    driver: bridge

services:
  db:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    container_name: mariadba8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - docker_mariadb_data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmina8
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "7008:80"
    depends_on:
      - db
    networks:
      - appnet

  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: fastapi
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PYTHONBUFFERED: 1
      CONNECTION_TRIES: ${CONNECTION_TRIES}
      EXPIRATION_MINUTES: ${EXPIRATION_MINUTES}
      SECRET_KEY: ${SECRET_KEY}
      PAGE_SIZE: ${PAGE_SIZE}
      MAX_IMAGE_SIZE: ${MAX_IMAGE_SIZE}
      DEBUG: ${DEBUG}
    volumes:
      - ./fastapi/app:/fastapi/app
    networks:
      - appnet

  apache:
    build: ./apache
    container_name: apachea8
    ports:
      - "6008:80"
      - "6448:443"
    volumes:
      - ./apache/conf/modsecurity:/etc/modsecurity
    depends_on:
      - db
      - fastapi
    networks:
      - appnet

volumes:
  docker_mariadb_data:
    driver: local
